<?php

namespace App\database\seeders;

use App\Models\City;
use App\Models\Province;

class LocationSeeder
{

    public function seedProvinces()
    {
        $provinces = [
            'تهران',
            'بوشهر',
            'ایلام',
            'چهارمحال و بختیاری',
            'البرز',
            'اصفهان',
            'اردبیل',
            'آذربایجان غربی',
            'آذربایجان شرقی',
            'سمنان',
            'زنجان',
            'خوزستان',
            'خراسان شمالی',
            'خراسان رضوی',
            'خراسان جنوبی',
            'کهگیلویه و بویراحمد',
            'کرمانشاه',
            'کرمان',
            'کردستان',
            'قم',
            'قزوین',
            'فارس',
            'سیستان و بلوچستان',
            'یزد',
            'همدان',
            'هرمزگان',
            'مازندران',
            'گلستان',
            'گیلان',
            'لرستان',
            'مرکزی',
        ];

        foreach ($provinces as $key => $item) {
            $n = new Province();

        }
    }

    public function seedCities()
    {
        $cities = [

            ['title' => 'تهران', 'province_id' => '1',],
            ['title' => 'اسلام‌شهر', 'province_id' => '1',],
            ['title' => 'قرچک', 'province_id' => '1',],
            ['title' => 'گلستان', 'province_id' => '1',],
            ['title' => 'قدس', 'province_id' => '1',],
            ['title' => 'ملارد', 'province_id' => '1',],
            ['title' => 'ورامین', 'province_id' => '1',],
            ['title' => 'شهریار', 'province_id' => '1',],
            ['title' => 'نسیم‌شهر', 'province_id' => '1',],
            ['title' => 'پاکدشت', 'province_id' => '1',],
            ['title' => 'اندیشه', 'province_id' => '1',],
            ['title' => 'رباط‌کریم', 'province_id' => '1',],
            ['title' => 'صالح‌آباد', 'province_id' => '1',],
            ['title' => 'باقرشهر', 'province_id' => '1',],
            ['title' => 'باغستان', 'province_id' => '1',],
            ['title' => 'بومهن', 'province_id' => '1',],
            ['title' => 'چهاردانگه', 'province_id' => '1',],
            ['title' => 'پیشوا', 'province_id' => '1',],
            ['title' => 'دماوند', 'province_id' => '1',],
            ['title' => 'پردیس', 'province_id' => '1',],
            ['title' => 'وحیدیه', 'province_id' => '1',],
            ['title' => 'نصیرآباد', 'province_id' => '1',],
            ['title' => 'فردوسیه', 'province_id' => '1',],
            ['title' => 'حسن‌آباد', 'province_id' => '1',],
            ['title' => 'رودهن', 'province_id' => '1',],
            ['title' => 'شاهدشهر', 'province_id' => '1',],
            ['title' => 'صباشهر', 'province_id' => '1',],
            ['title' => 'صفادشت', 'province_id' => '1',],
            ['title' => 'فیروزکوه', 'province_id' => '1',],
            ['title' => 'لواسان', 'province_id' => '1',],
            ['title' => 'آبسرد', 'province_id' => '1',],
            ['title' => 'شریف‌آباد', 'province_id' => '1',],
            ['title' => 'کهریزک', 'province_id' => '1',],
            ['title' => 'فشم', 'province_id' => '1',],
            ['title' => 'جوادآباد', 'province_id' => '1',],
            ['title' => 'کیلان', 'province_id' => '1',],
            ['title' => 'آبعلی', 'province_id' => '1',],
            ['title' => 'ارجمند', 'province_id' => '1',],

            ['title' => 'بندر بوشهر', 'province_id' => '2',],
            ['title' => 'بندر کنگان', 'province_id' => '2',],
            ['title' => 'خورموج', 'province_id' => '2',],
            ['title' => 'بندر دیلم', 'province_id' => '2',],
            ['title' => 'بندر دیر', 'province_id' => '2',],
            ['title' => 'چغادک', 'province_id' => '2',],
            ['title' => 'آب‌پخش', 'province_id' => '2',],
            ['title' => 'جم', 'province_id' => '2',],
            ['title' => 'اهرم', 'province_id' => '2',],
            ['title' => 'عالی‌شهر', 'province_id' => '2',],
            ['title' => 'بنک', 'province_id' => '2',],
            ['title' => 'نخل تقی', 'province_id' => '2',],
            ['title' => 'وحدتیه', 'province_id' => '2',],
            ['title' => 'کاکی', 'province_id' => '2',],
            ['title' => 'عسلویه', 'province_id' => '2',],
            ['title' => 'سعدآباد', 'province_id' => '2',],
            ['title' => 'شبانکاره', 'province_id' => '2',],
            ['title' => 'خارک', 'province_id' => '2',],
            ['title' => 'بندر سیراف', 'province_id' => '2',],
            ['title' => 'آبدان', 'province_id' => '2',],
            ['title' => 'بردستان', 'province_id' => '2',],
            ['title' => 'دالکی', 'province_id' => '2',],
            ['title' => 'بندر ریگ', 'province_id' => '2',],
            ['title' => 'دوراهک', 'province_id' => '2',],
            ['title' => 'بردخون', 'province_id' => '2',],
            ['title' => 'دلوار', 'province_id' => '2',],
            ['title' => 'بادوله', 'province_id' => '2',],
            ['title' => 'آباد', 'province_id' => '2',],
            ['title' => 'تنگ ارم', 'province_id' => '2',],
            ['title' => 'انارستان', 'province_id' => '2',],
            ['title' => 'شُنبه', 'province_id' => '2',],
            ['title' => 'امام حسن', 'province_id' => '2',],
            ['title' => 'ریز', 'province_id' => '2',],
            ['title' => 'بوشکان', 'province_id' => '2',],
            ['title' => 'کلمه', 'province_id' => '2',],

            ['title' => 'ایلام', 'province_id' => '3',],
            ['title' => 'ایوان', 'province_id' => '3',],
            ['title' => 'دهلران', 'province_id' => '3',],
            ['title' => 'آبدانان', 'province_id' => '3',],
            ['title' => 'دره‌شهر', 'province_id' => '3',],
            ['title' => 'ارکواز', 'province_id' => '3',],
            ['title' => 'مهران', 'province_id' => '3',],
            ['title' => 'سرابله', 'province_id' => '3',],
            ['title' => 'آسمان‌آباد', 'province_id' => '3',],
            ['title' => 'چوار', 'province_id' => '3',],
            ['title' => 'پهله', 'province_id' => '3',],
            ['title' => 'دلگشا', 'province_id' => '3',],
            ['title' => 'بدره', 'province_id' => '3',],
            ['title' => 'مورموری', 'province_id' => '3',],
            ['title' => 'زرنه', 'province_id' => '3',],
            ['title' => 'لومار', 'province_id' => '3',],
            ['title' => 'موسیان', 'province_id' => '3',],
            ['title' => 'میمه', 'province_id' => '3',],
            ['title' => 'سراب‌باغ', 'province_id' => '3',],
            ['title' => 'صالح‌آباد', 'province_id' => '3',],
            ['title' => 'توحید', 'province_id' => '3',],

            ['title' => 'شهرکرد', 'province_id' => '4',],
            ['title' => 'بروجن', 'province_id' => '4',],
            ['title' => 'فرخ‌شهر', 'province_id' => '4',],
            ['title' => 'فارسان', 'province_id' => '4',],
            ['title' => 'لردگان', 'province_id' => '4',],
            ['title' => 'هفشجان', 'province_id' => '4',],
            ['title' => 'سامان', 'province_id' => '4',],
            ['title' => 'جونقان', 'province_id' => '4',],
            ['title' => 'فرادنبه', 'province_id' => '4',],
            ['title' => 'بن', 'province_id' => '4',],
            ['title' => 'سورشجان', 'province_id' => '4',],
            ['title' => 'باباحیدر', 'province_id' => '4',],
            ['title' => 'کیان', 'province_id' => '4',],
            ['title' => 'بلداجی', 'province_id' => '4',],
            ['title' => 'اردل', 'province_id' => '4',],
            ['title' => 'نقنه', 'province_id' => '4',],
            ['title' => 'شلمزار', 'province_id' => '4',],
            ['title' => 'گهرو', 'province_id' => '4',],
            ['title' => 'سفیددشت', 'province_id' => '4',],
            ['title' => 'گندمان', 'province_id' => '4',],
            ['title' => 'طاقانک', 'province_id' => '4',],
            ['title' => 'سودجان', 'province_id' => '4',],
            ['title' => 'ناغان', 'province_id' => '4',],
            ['title' => 'نافچ', 'province_id' => '4',],
            ['title' => 'مال‌خلیفه', 'province_id' => '4',],
            ['title' => 'چلگرد', 'province_id' => '4',],
            ['title' => 'آلونی', 'province_id' => '4',],

            ['title' => 'کرج', 'province_id' => '5',],
            ['title' => 'نظرآباد', 'province_id' => '5',],
            ['title' => 'محمدشهر', 'province_id' => '5',],
            ['title' => 'کمال‌شهر', 'province_id' => '5',],
            ['title' => 'هشتگرد', 'province_id' => '5',],
            ['title' => 'مشکین‌دشت', 'province_id' => '5',],
            ['title' => 'ماهدشت', 'province_id' => '5',],
            ['title' => 'اشتهارد', 'province_id' => '5',],
            ['title' => 'شهر جدید هشتگرد', 'province_id' => '5',],
            ['title' => 'گرمدره', 'province_id' => '5',],
            ['title' => 'کوهسار', 'province_id' => '5',],
            ['title' => 'چهارباغ', 'province_id' => '5',],
            ['title' => 'طالقان', 'province_id' => '5',],
            ['title' => 'آسارا', 'province_id' => '5',],

            ['title' => 'اصفهان', 'province_id' => '6',],
            ['title' => 'کاشان', 'province_id' => '6',],
            ['title' => 'خمینی شهر', 'province_id' => '6',],
            ['title' => 'نجف آباد', 'province_id' => '6',],
            ['title' => 'شاهین شهر', 'province_id' => '6',],
            ['title' => 'شهرضا', 'province_id' => '6',],
            ['title' => 'خوراسگان', 'province_id' => '6',],
            ['title' => 'فولادشهر', 'province_id' => '6',],
            ['title' => 'مبارکه', 'province_id' => '6',],
            ['title' => 'بهارستان', 'province_id' => '6',],
            ['title' => 'آران و بیدگل', 'province_id' => '6',],
            ['title' => 'زرین شهر', 'province_id' => '6',],
            ['title' => 'گلپایگان', 'province_id' => '6',],
            ['title' => 'درچه پیاز', 'province_id' => '6',],
            ['title' => 'فلاورجان', 'province_id' => '6',],
            ['title' => 'دولت آباد', 'province_id' => '6',],
            ['title' => 'قهدریجان', 'province_id' => '6',],
            ['title' => 'نایین', 'province_id' => '6',],
            ['title' => 'سمیرم', 'province_id' => '6',],
            ['title' => 'کلیشاد و سودرجان', 'province_id' => '6',],
            ['title' => 'گل‌دشت', 'province_id' => '6',],
            ['title' => 'خورزوق', 'province_id' => '6',],
            ['title' => 'ابریشم', 'province_id' => '6',],
            ['title' => 'خوانسار', 'province_id' => '6',],
            ['title' => 'گز', 'province_id' => '6',],

            ['title' => 'اردبیل', 'province_id' => '7',],
            ['title' => 'پارس‌آباد', 'province_id' => '7',],
            ['title' => 'مشگین‌شهر', 'province_id' => '7',],
            ['title' => 'خلخال', 'province_id' => '7',],
            ['title' => 'گرمی', 'province_id' => '7',],
            ['title' => 'بیله‌سوار', 'province_id' => '7',],
            ['title' => 'نمین', 'province_id' => '7',],
            ['title' => 'جعفرآباد', 'province_id' => '7',],
            ['title' => 'جعفرآباد', 'province_id' => '7',],
            ['title' => 'عنبران', 'province_id' => '7',],
            ['title' => 'آبی‌بیگلو', 'province_id' => '7',],
            ['title' => 'نیر', 'province_id' => '7',],
            ['title' => 'هشجین', 'province_id' => '7',],
            ['title' => 'اصلاندوز', 'province_id' => '7',],
            ['title' => 'سرعین', 'province_id' => '7',],
            ['title' => 'تازه‌کند', 'province_id' => '7',],
            ['title' => 'لاهرود', 'province_id' => '7',],
            ['title' => 'تازه‌کند انگوت', 'province_id' => '7',],
            ['title' => 'هیر', 'province_id' => '7',],
            ['title' => 'کلور', 'province_id' => '7',],
            ['title' => 'رضی', 'province_id' => '7',],
            ['title' => 'فخرآباد', 'province_id' => '7',],
            ['title' => 'کوراییم', 'province_id' => '7',],
            ['title' => 'مرادلو', 'province_id' => '7',],


            ['title' => 'ارومیه', 'province_id' => '8',],
            ['title' => 'خوی', 'province_id' => '8',],
            ['title' => 'بوکان', 'province_id' => '8',],
            ['title' => 'مهاباد', 'province_id' => '8',],
            ['title' => 'میاندوآب', 'province_id' => '8',],
            ['title' => 'سلماس', 'province_id' => '8',],
            ['title' => 'نقده', 'province_id' => '8',],
            ['title' => 'پیرانشهر', 'province_id' => '8',],
            ['title' => 'تکاب', 'province_id' => '8',],
            ['title' => 'ماکو', 'province_id' => '8',],
            ['title' => 'سردشت', 'province_id' => '8',],
            ['title' => 'شاهین‌دژ', 'province_id' => '8',],
            ['title' => 'اشنویه', 'province_id' => '8',],
            ['title' => 'قره‌ضیاءالدین', 'province_id' => '8',],
            ['title' => 'شوط', 'province_id' => '8',],
            ['title' => 'سیه‌چشمه', 'province_id' => '8',],
            ['title' => 'ربط', 'province_id' => '8',],
            ['title' => 'پلدشت', 'province_id' => '8',],
            ['title' => 'بازرگان', 'province_id' => '8',],
            ['title' => 'تازه‌شهر', 'province_id' => '8',],
            ['title' => 'فیرورق', 'province_id' => '8',],
            ['title' => 'چهاربرج', 'province_id' => '8',],
            ['title' => 'محمدیار', 'province_id' => '8',],
            ['title' => 'دیزج دیز', 'province_id' => '8',],
            ['title' => 'نوشین‌شهر', 'province_id' => '8',],
            ['title' => 'محمودآباد', 'province_id' => '8',],
            ['title' => 'میرآباد', 'province_id' => '8',],
            ['title' => 'قطور', 'province_id' => '8',],
            ['title' => 'باروق', 'province_id' => '8',],
            ['title' => 'کشاورز', 'province_id' => '8',],
            ['title' => 'ایواوغلی', 'province_id' => '8',],
            ['title' => 'نالوس', 'province_id' => '8',],
            ['title' => 'نازک علیا', 'province_id' => '8',],
            ['title' => 'قوشچی', 'province_id' => '8',],
            ['title' => 'مرگنلر', 'province_id' => '8',],
            ['title' => 'گردکشانه', 'province_id' => '8',],
            ['title' => 'سرو', 'province_id' => '8',],
            ['title' => 'آواجیق', 'province_id' => '8',],
            ['title' => 'سیلوانه', 'province_id' => '8',],
            ['title' => 'زرآباد', 'province_id' => '8',],
            ['title' => 'سیمینه', 'province_id' => '8',],
            ['title' => 'خلیفان', 'province_id' => '8',],

            ['title' => 'تبریز', 'province_id' => '9',],
            ['title' => 'مراغه', 'province_id' => '9',],
            ['title' => 'مرند', 'province_id' => '9',],
            ['title' => 'اهر', 'province_id' => '9',],
            ['title' => 'بناب', 'province_id' => '9',],
            ['title' => 'میانه', 'province_id' => '9',],
            ['title' => 'سراب', 'province_id' => '9',],
            ['title' => 'آذرشهر', 'province_id' => '9',],
            ['title' => 'هادیشهر', 'province_id' => '9',],
            ['title' => 'سردرود', 'province_id' => '9',],
            ['title' => 'عجب‌شیر', 'province_id' => '9',],
            ['title' => 'ملکان', 'province_id' => '9',],
            ['title' => 'سهند', 'province_id' => '9',],
            ['title' => 'هشترود', 'province_id' => '9',],
            ['title' => 'بستان‌آباد', 'province_id' => '9',],
            ['title' => 'اسکو', 'province_id' => '9',],
            ['title' => 'شبستر', 'province_id' => '9',],
            ['title' => 'ایلخچی', 'province_id' => '9',],
            ['title' => 'ممقان', 'province_id' => '9',],
            ['title' => 'خسروشاه', 'province_id' => '9',],
            ['title' => 'گوگان', 'province_id' => '9',],
            ['title' => 'باسمنج', 'province_id' => '9',],
            ['title' => 'کلیبر', 'province_id' => '9',],
            ['title' => 'یامچی', 'province_id' => '9',],
            ['title' => 'هریس', 'province_id' => '9',],
            ['title' => 'صوفیان', 'province_id' => '9',],
            ['title' => 'شندآباد', 'province_id' => '9',],
            ['title' => 'کشکسرای', 'province_id' => '9',],
            ['title' => 'تسوج', 'province_id' => '9',],
            ['title' => 'ترکمانچای', 'province_id' => '9',],
            ['title' => 'کلوانق', 'province_id' => '9',],
            ['title' => 'لیلان', 'province_id' => '9',],
            ['title' => 'بخشایش', 'province_id' => '9',],
            ['title' => 'مهربان', 'province_id' => '9',],
            ['title' => 'زرنق', 'province_id' => '9',],
            ['title' => 'قره‌آغاج', 'province_id' => '9',],
            ['title' => 'جلفا', 'province_id' => '9',],
            ['title' => 'سیس', 'province_id' => '9',],
            ['title' => 'ورزقان', 'province_id' => '9',],
            ['title' => 'تیمورلو', 'province_id' => '9',],
            ['title' => 'شربیان', 'province_id' => '9',],
            ['title' => 'هوراند', 'province_id' => '9',],
            ['title' => 'بناب مرند', 'province_id' => '9',],
            ['title' => 'وایقان', 'province_id' => '9',],
            ['title' => 'مبارک‌شهر', 'province_id' => '9',],
            ['title' => 'دوزدوزان', 'province_id' => '9',],
            ['title' => 'خواجه', 'province_id' => '9',],
            ['title' => 'آچاچی', 'province_id' => '9',],
            ['title' => 'شرفخانه', 'province_id' => '9',],
            ['title' => 'کوزه‌کنان', 'province_id' => '9',],
            ['title' => 'تیکمه‌داش', 'province_id' => '9',],
            ['title' => 'زنوز', 'province_id' => '9',],
            ['title' => 'خامنه', 'province_id' => '9',],
            ['title' => 'ترک', 'province_id' => '9',],
            ['title' => 'آبش‌احمد', 'province_id' => '9',],
            ['title' => 'آقکند', 'province_id' => '9',],
            ['title' => 'خمارلو', 'province_id' => '9',],
            ['title' => 'خداجو', 'province_id' => '9',],
            ['title' => 'سیه‌رود', 'province_id' => '9',],
            ['title' => 'خاروانا', 'province_id' => '9',],
            ['title' => 'نظرکهریزی', 'province_id' => '9',],
            ['title' => 'جوان‌قلعه', 'province_id' => '9',],

            ['title' => 'سمنان', 'province_id' => '10',],
            ['title' => 'شاهرود', 'province_id' => '10',],
            ['title' => 'دامغان', 'province_id' => '10',],
            ['title' => 'گرمسار', 'province_id' => '10',],
            ['title' => 'مهدی‌شهر', 'province_id' => '10',],
            ['title' => 'سرخه', 'province_id' => '10',],
            ['title' => 'ایوانکی', 'province_id' => '10',],
            ['title' => 'شهمیرزاد', 'province_id' => '10',],
            ['title' => 'بسطام', 'province_id' => '10',],
            ['title' => 'آرادان', 'province_id' => '10',],
            ['title' => 'مجن', 'province_id' => '10',],
            ['title' => 'کلاته خیج', 'province_id' => '10',],
            ['title' => 'درجزین', 'province_id' => '10',],
            ['title' => 'میامی', 'province_id' => '10',],
            ['title' => 'دیباج', 'province_id' => '10',],
            ['title' => 'بیارجمند', 'province_id' => '10',],
            ['title' => 'امیریه', 'province_id' => '10',],

            ['title' => 'زنجان', 'province_id' => '11',],
            ['title' => 'ابهر', 'province_id' => '11',],
            ['title' => 'خرمدره', 'province_id' => '11',],
            ['title' => 'قیدار', 'province_id' => '11',],
            ['title' => 'هیدج', 'province_id' => '11',],
            ['title' => 'صائین‌قلعه', 'province_id' => '11',],
            ['title' => 'سلطانیه', 'province_id' => '11',],
            ['title' => 'آب بر', 'province_id' => '11',],
            ['title' => 'سجاس', 'province_id' => '11',],
            ['title' => 'سهرورد', 'province_id' => '11',],
            ['title' => 'زرین رود', 'province_id' => '11',],
            ['title' => 'ماه‌نشان', 'province_id' => '11',],
            ['title' => 'کرسف', 'province_id' => '11',],
            ['title' => 'گرماب', 'province_id' => '11',],
            ['title' => 'دندی', 'province_id' => '11',],
            ['title' => 'نوربهار', 'province_id' => '11',],
            ['title' => 'زرین‌آباد', 'province_id' => '11',],
            ['title' => 'ارمغان خانه', 'province_id' => '11',],
            ['title' => 'چورزق', 'province_id' => '11',],
            ['title' => 'حلب', 'province_id' => '11',],
            ['title' => 'نیک پی', 'province_id' => '11',],

            ['title' => 'آبادان', 'province_id' => '12',],
            ['title' => 'باغ ملک', 'province_id' => '12',],
            ['title' => 'دزفول', 'province_id' => '12',],
            ['title' => 'شوش', 'province_id' => '12',],
            ['title' => 'اندیمشک', 'province_id' => '12',],
            ['title' => 'بندر ماهشهر', 'province_id' => '12',],
            ['title' => 'رامهرمز', 'province_id' => '12',],
            ['title' => 'شوشتر', 'province_id' => '12',],
            ['title' => 'اهواز', 'province_id' => '12',],
            ['title' => 'بهبهان', 'province_id' => '12',],
            ['title' => 'سوسنگرد', 'province_id' => '12',],
            ['title' => 'مسجد سلیمان', 'province_id' => '12',],
            ['title' => 'ایذه', 'province_id' => '12',],
            ['title' => 'خرمشهر', 'province_id' => '12',],
            ['title' => 'شادگان', 'province_id' => '12',],

            ['title' => 'بجنورد', 'province_id' => '13',],
            ['title' => 'شیروان', 'province_id' => '13',],
            ['title' => 'اسفراین', 'province_id' => '13',],
            ['title' => 'گرمه جاجرم', 'province_id' => '13',],
            ['title' => 'آشخانه', 'province_id' => '13',],
            ['title' => 'فاروج', 'province_id' => '13',],
            ['title' => 'راز', 'province_id' => '13',],
            ['title' => 'درق', 'province_id' => '13',],
            ['title' => 'صفی‌آباد', 'province_id' => '13',],
            ['title' => 'قاضی', 'province_id' => '13',],
            ['title' => 'شوقان', 'province_id' => '13',],
            ['title' => 'سنخواست', 'province_id' => '13',],
            ['title' => 'پیش‌قلعه', 'province_id' => '13',],
            ['title' => 'حصار گرم‌خان', 'province_id' => '13',],
            ['title' => 'لوجلی', 'province_id' => '13',],

            ['title' => 'مشهد', 'province_id' => '14',],
            ['title' => 'سبزوار', 'province_id' => '14',],
            ['title' => 'نیشابور', 'province_id' => '14',],
            ['title' => 'تربت حیدریه', 'province_id' => '14',],
            ['title' => 'قوچان', 'province_id' => '14',],
            ['title' => 'تربت جام', 'province_id' => '14',],
            ['title' => 'کاشمر', 'province_id' => '14',],
            ['title' => 'تایباد', 'province_id' => '14',],
            ['title' => 'چناران', 'province_id' => '14',],
            ['title' => 'گناباد', 'province_id' => '14',],
            ['title' => 'درگز', 'province_id' => '14',],
            ['title' => 'سرخس', 'province_id' => '14',],
            ['title' => 'فریمان', 'province_id' => '14',],
            ['title' => 'بردسکن', 'province_id' => '14',],
            ['title' => 'خواف', 'province_id' => '14',],
            ['title' => 'فیض‌آباد', 'province_id' => '14',],
            ['title' => 'طرقبه', 'province_id' => '14',],
            ['title' => 'نقاب', 'province_id' => '14',],
            ['title' => 'بجستان', 'province_id' => '14',],
            ['title' => 'خرو', 'province_id' => '14',],
            ['title' => 'کاریز', 'province_id' => '14',],
            ['title' => 'دولت‌آباد', 'province_id' => '14',],
            ['title' => 'صالح‌آباد', 'province_id' => '14',],
            ['title' => 'سنگان', 'province_id' => '14',],
            ['title' => 'خلیل‌آباد', 'province_id' => '14',],
            ['title' => 'مشهدریزه', 'province_id' => '14',],
            ['title' => 'باخرز', 'province_id' => '14',],
            ['title' => 'کلات', 'province_id' => '14',],
            ['title' => 'نصرآباد', 'province_id' => '14',],
            ['title' => 'جغتای', 'province_id' => '14',],
            ['title' => 'نیل‌شهر', 'province_id' => '14',],
            ['title' => 'فرهادگرد', 'province_id' => '14',],
            ['title' => 'شاندیز', 'province_id' => '14',],
            ['title' => 'نشتیفان', 'province_id' => '14',],
            ['title' => 'گلمکان', 'province_id' => '14',],
            ['title' => 'انابد', 'province_id' => '14',],

            ['title' => 'بیرجند', 'province_id' => '15',],
            ['title' => 'قائن', 'province_id' => '15',],
            ['title' => 'طبس', 'province_id' => '15',],
            ['title' => 'فردوس', 'province_id' => '15',],
            ['title' => 'نهبندان', 'province_id' => '15',],
            ['title' => 'بشرویه', 'province_id' => '15',],
            ['title' => 'سرایان', 'province_id' => '15',],
            ['title' => 'سربیشه', 'province_id' => '15',],
            ['title' => 'اسلامیه', 'province_id' => '15',],
            ['title' => 'حاجی‌آباد', 'province_id' => '15',],
            ['title' => 'اسدیه', 'province_id' => '15',],
            ['title' => 'خضری دشت بیاض', 'province_id' => '15',],
            ['title' => 'خوسف', 'province_id' => '15',],
            ['title' => 'آیسک', 'province_id' => '15',],
            ['title' => 'عشق‌آباد', 'province_id' => '15',],
            ['title' => 'نیمبلوک', 'province_id' => '15',],
            ['title' => 'سه‌قلعه', 'province_id' => '15',],
            ['title' => 'طبس مسینا', 'province_id' => '15',],
            ['title' => 'آرین‌شهر', 'province_id' => '15',],
            ['title' => 'اسفدن', 'province_id' => '15',],
            ['title' => 'دیهوک', 'province_id' => '15',],
            ['title' => 'مود', 'province_id' => '15',],
            ['title' => 'قهستان', 'province_id' => '15',],
            ['title' => 'شوسف', 'province_id' => '15',],
            ['title' => 'ارسک', 'province_id' => '15',],
            ['title' => 'گزیک', 'province_id' => '15',],
            ['title' => 'محمدشهر', 'province_id' => '15',],
            ['title' => 'زهان', 'province_id' => '15',],

            ['title' => 'یاسوج', 'province_id' => '16',],
            ['title' => 'دوگنبدان', 'province_id' => '16',],
            ['title' => 'دهدشت', 'province_id' => '16',],
            ['title' => 'لیکک', 'province_id' => '16',],
            ['title' => 'چرام', 'province_id' => '16',],
            ['title' => 'لنده', 'province_id' => '16',],
            ['title' => 'باشت', 'province_id' => '16',],
            ['title' => 'سی‌سخت', 'province_id' => '16',],
            ['title' => 'سوق', 'province_id' => '16',],
            ['title' => 'دیشموک', 'province_id' => '16',],
            ['title' => 'سرفاریاب', 'province_id' => '16',],
            ['title' => 'قلعه ریسی', 'province_id' => '16',],
            ['title' => 'مارگون', 'province_id' => '16',],
            ['title' => 'پاتاوه', 'province_id' => '16',],
            ['title' => 'چیتاب', 'province_id' => '16',],
            ['title' => 'گراب سفلی', 'province_id' => '16',],

            ['title' => 'کرمانشاه', 'province_id' => '17',],
            ['title' => 'صحنه', 'province_id' => '17',],
            ['title' => 'اسلام آباد غرب', 'province_id' => '17',],
            ['title' => 'سنقر', 'province_id' => '17',],
            ['title' => 'کنگاور', 'province_id' => '17',],
            ['title' => 'پاوه', 'province_id' => '17',],
            ['title' => 'گیلانغرب', 'province_id' => '17',],
            ['title' => 'جوانرود', 'province_id' => '17',],
            ['title' => 'قصر شیرین', 'province_id' => '17',],
            ['title' => 'هرسین', 'province_id' => '17',],
            ['title' => 'سریل ذهاب', 'province_id' => '17',],
            ['title' => 'آران کنگاور', 'province_id' => '17',],
            ['title' => 'باوله', 'province_id' => '17',],
            ['title' => 'بیستون', 'province_id' => '17',],
            ['title' => 'چورزی', 'province_id' => '17',],
            ['title' => 'حسن آباد روانسر', 'province_id' => '17',],
            ['title' => 'دشه', 'province_id' => '17',],
            ['title' => 'ساتیاری', 'province_id' => '17',],
            ['title' => 'سهنله', 'province_id' => '17',],
            ['title' => 'شهرک صنعتی فرامان', 'province_id' => '17',],
            ['title' => 'قارلق', 'province_id' => '17',],
            ['title' => 'کارخانه', 'province_id' => '17',],
            ['title' => 'کوزران', 'province_id' => '17',],
            ['title' => 'میان راهان', 'province_id' => '17',],
            ['title' => 'ارمنی جان', 'province_id' => '17',],
            ['title' => 'باینگان', 'province_id' => '17',],
            ['title' => 'پریوه', 'province_id' => '17',],
            ['title' => 'چهر', 'province_id' => '17',],
            ['title' => 'حمیل', 'province_id' => '17',],
            ['title' => 'دهر', 'province_id' => '17',],
            ['title' => 'سرمان حسین خانی', 'province_id' => '17',],
            ['title' => 'شمشیر', 'province_id' => '17',],
            ['title' => 'علی آباد', 'province_id' => '17',],
            ['title' => 'قزانچی', 'province_id' => '17',],
            ['title' => 'کرند غرب', 'province_id' => '17',],
            ['title' => 'گوسفید', 'province_id' => '17',],
            ['title' => 'میرآباد', 'province_id' => '17',],
            ['title' => 'بانمزاران', 'province_id' => '17',],
            ['title' => 'بلوردی', 'province_id' => '17',],
            ['title' => 'تازه آباد', 'province_id' => '17',],
            ['title' => 'حریر', 'province_id' => '17',],
            ['title' => 'خسروی', 'province_id' => '17',],
            ['title' => 'رحمت آباد', 'province_id' => '17',],
            ['title' => 'سطر', 'province_id' => '17',],
            ['title' => 'شهر صنعتی باختران', 'province_id' => '17',],
            ['title' => 'فارسینج', 'province_id' => '17',],
            ['title' => 'کل کش', 'province_id' => '17',],
            ['title' => 'گهواره', 'province_id' => '17',],
            ['title' => 'نودشه', 'province_id' => '17',],
            ['title' => 'بانه وره', 'province_id' => '17',],
            ['title' => 'بیدسرخ', 'province_id' => '17',],
            ['title' => 'جیحون آباد', 'province_id' => '17',],
            ['title' => 'جحسن آباد اسلام آباد', 'province_id' => '17',],
            ['title' => 'درکه و عین القاس', 'province_id' => '17',],
            ['title' => 'روانسر', 'province_id' => '17',],
            ['title' => 'سومار', 'province_id' => '17',],
            ['title' => 'شهرک شهید عسگری گاوبنده', 'province_id' => '17',],
            ['title' => 'شفش', 'province_id' => '17',],
            ['title' => 'قلعه شیان', 'province_id' => '17',],
            ['title' => 'کندوله', 'province_id' => '17',],
            ['title' => 'ماهیدشت', 'province_id' => '17',],
            ['title' => 'نوسود', 'province_id' => '17',],

            ['title' => 'کرمان', 'province_id' => '18',],
            ['title' => 'سیرجان', 'province_id' => '18',],
            ['title' => 'رفسنجان', 'province_id' => '18',],
            ['title' => 'جیرفت', 'province_id' => '18',],
            ['title' => 'بم', 'province_id' => '18',],
            ['title' => 'زرند', 'province_id' => '18',],
            ['title' => 'شهربابک', 'province_id' => '18',],
            ['title' => 'کهنوج', 'province_id' => '18',],
            ['title' => 'بافت', 'province_id' => '18',],
            ['title' => 'بردسیر', 'province_id' => '18',],
            ['title' => 'راور', 'province_id' => '18',],
            ['title' => 'عنبرآباد', 'province_id' => '18',],
            ['title' => 'بروات', 'province_id' => '18',],
            ['title' => 'ماهان', 'province_id' => '18',],
            ['title' => 'منوجان', 'province_id' => '18',],
            ['title' => 'انار', 'province_id' => '18',],
            ['title' => 'قلعه گنج', 'province_id' => '18',],
            ['title' => 'رودبار', 'province_id' => '18',],
            ['title' => 'فهرج', 'province_id' => '18',],
            ['title' => 'رابر', 'province_id' => '18',],
            ['title' => 'کوهبنان', 'province_id' => '18',],
            ['title' => 'راین', 'province_id' => '18',],
            ['title' => 'محمدآباد', 'province_id' => '18',],
            ['title' => 'نجف شهر', 'province_id' => '18',],
            ['title' => 'گلباف', 'province_id' => '18',],

            ['title' => 'سنندج', 'province_id' => '19',],
            ['title' => 'سقز', 'province_id' => '19',],
            ['title' => 'مریوان', 'province_id' => '19',],
            ['title' => 'بانه', 'province_id' => '19',],
            ['title' => 'قروه', 'province_id' => '19',],
            ['title' => 'کامیاران', 'province_id' => '19',],
            ['title' => 'بیجار', 'province_id' => '19',],
            ['title' => 'دیواندره', 'province_id' => '19',],
            ['title' => 'دهگلان', 'province_id' => '19',],
            ['title' => 'کانی‌دینار', 'province_id' => '19',],
            ['title' => 'سریش‌آباد', 'province_id' => '19',],
            ['title' => 'دلبران', 'province_id' => '19',],
            ['title' => 'سروآباد', 'province_id' => '19',],
            ['title' => 'بلبان‌آباد', 'province_id' => '19',],
            ['title' => 'یاسوکند', 'province_id' => '19',],
            ['title' => 'موچش', 'province_id' => '19',],
            ['title' => 'دزج', 'province_id' => '19',],
            ['title' => 'آرمرده', 'province_id' => '19',],
            ['title' => 'صاحب', 'province_id' => '19',],
            ['title' => 'زرینه', 'province_id' => '19',],
            ['title' => 'شویشه', 'province_id' => '19',],
            ['title' => 'کانی‌سور', 'province_id' => '19',],
            ['title' => 'بویین سفلی', 'province_id' => '19',],
            ['title' => 'بابارشانی', 'province_id' => '19',],

            ['title' => 'قم', 'province_id' => '20',],
            ['title' => 'قنوات', 'province_id' => '20',],
            ['title' => 'جعفریه', 'province_id' => '20',],
            ['title' => 'کهک', 'province_id' => '20',],
            ['title' => 'دستجرد', 'province_id' => '20',],
            ['title' => 'سلفچگان', 'province_id' => '20',],

            ['title' => 'قزوین', 'province_id' => '21',],
            ['title' => 'تاکستان', 'province_id' => '21',],
            ['title' => 'الوند', 'province_id' => '21',],
            ['title' => 'اقبالیه', 'province_id' => '21',],
            ['title' => 'آبیک', 'province_id' => '21',],
            ['title' => 'محمدیه', 'province_id' => '21',],
            ['title' => 'بیدستان', 'province_id' => '21',],
            ['title' => 'محمودآباد نمونه', 'province_id' => '21',],
            ['title' => 'بویین‌زهرا', 'province_id' => '21',],
            ['title' => 'شال', 'province_id' => '21',],
            ['title' => 'اسفرورین', 'province_id' => '21',],
            ['title' => 'آبگرم', 'province_id' => '21',],
            ['title' => 'دانسفهان', 'province_id' => '21',],
            ['title' => 'ضیاءآباد', 'province_id' => '21',],
            ['title' => 'خرمدشت', 'province_id' => '21',],
            ['title' => 'نرجه', 'province_id' => '21',],
            ['title' => 'سگزآباد', 'province_id' => '21',],
            ['title' => 'ارداق', 'province_id' => '21',],
            ['title' => 'آوج', 'province_id' => '21',],
            ['title' => 'خاکعلی', 'province_id' => '21',],
            ['title' => 'معلم‌کلایه', 'province_id' => '21',],
            ['title' => 'کوهین', 'province_id' => '21',],
            ['title' => 'رازمیان', 'province_id' => '21',],
            ['title' => 'سیردان', 'province_id' => '21',],

            ['title' => 'شیراز', 'province_id' => '22',],
            ['title' => 'مرودشت', 'province_id' => '22',],
            ['title' => 'کازرون', 'province_id' => '22',],
            ['title' => 'لار', 'province_id' => '22',],
            ['title' => 'جهرم', 'province_id' => '22',],
            ['title' => 'فسا', 'province_id' => '22',],
            ['title' => 'داراب', 'province_id' => '22',],
            ['title' => 'فیروزآباد', 'province_id' => '22',],
            ['title' => 'نورآباد', 'province_id' => '22',],
            ['title' => 'نیریز', 'province_id' => '22',],
            ['title' => 'اقلید', 'province_id' => '22',],
            ['title' => 'آباده', 'province_id' => '22',],
            ['title' => 'اردکان', 'province_id' => '22',],
            ['title' => 'لامرد', 'province_id' => '22',],
            ['title' => 'کوار', 'province_id' => '22',],
            ['title' => 'حاجی آباد', 'province_id' => '22',],
            ['title' => 'استهبان', 'province_id' => '22',],
            ['title' => 'قیر', 'province_id' => '22',],
            ['title' => 'خرامه', 'province_id' => '22',],
            ['title' => 'مُهر', 'province_id' => '22',],
            ['title' => 'صفاشهر', 'province_id' => '22',],
            ['title' => 'بوانات', 'province_id' => '22',],
            ['title' => 'گراش', 'province_id' => '22',],
            ['title' => 'مصیری', 'province_id' => '22',],
            ['title' => 'فراشبند', 'province_id' => '22',],
            ['title' => 'ارسنجان', 'province_id' => '22',],
            ['title' => 'خنج', 'province_id' => '22',],
            ['title' => 'سروستان', 'province_id' => '22',],
            ['title' => 'سعادتشهر', 'province_id' => '22',],

            ['title' => 'زاهدان', 'province_id' => '23',],
            ['title' => 'ده یادگار', 'province_id' => '23',],
            ['title' => 'ابتر ایرانشهر', 'province_id' => '23',],
            ['title' => 'ادیمی زابل', 'province_id' => '23',],
            ['title' => 'اسپکه', 'province_id' => '23',],
            ['title' => 'آسپیچ محمدی', 'province_id' => '23',],
            ['title' => 'اسفند', 'province_id' => '23',],
            ['title' => 'اسفندک', 'province_id' => '23',],
            ['title' => 'اسماعیل‌آباد', 'province_id' => '23',],
            ['title' => 'اسماعیل قنبرتی', 'province_id' => '23',],
            ['title' => 'اسکل آباد', 'province_id' => '23',],
            ['title' => 'آشار زاهدان', 'province_id' => '23',],
            ['title' => 'ایرانشهر', 'province_id' => '23',],
            ['title' => 'باتک', 'province_id' => '23',],
            ['title' => 'بریس چابهار', 'province_id' => '23',],
            ['title' => 'بزمان گیمان', 'province_id' => '23',],
            ['title' => 'بمپور ایرانشهر', 'province_id' => '23',],
            ['title' => 'بنت', 'province_id' => '23',],
            ['title' => 'بنجار زابل', 'province_id' => '23',],
            ['title' => 'پارود چابهار', 'province_id' => '23',],
            ['title' => 'پایگاه هوائی (کنارک)', 'province_id' => '23',],
            ['title' => 'پزم چابهار', 'province_id' => '23',],
            ['title' => 'پسابندر', 'province_id' => '23',],
            ['title' => 'پسکوه سیب و سوران', 'province_id' => '23',],
            ['title' => 'پلان چابهار', 'province_id' => '23',],
            ['title' => 'پیپ ایرانشهر', 'province_id' => '23',],
            ['title' => 'پیشین چابهار', 'province_id' => '23',],
            ['title' => 'تمندان', 'province_id' => '23',],
            ['title' => 'جالق ایرانشهر', 'province_id' => '23',],
            ['title' => 'جزینک زابل', 'province_id' => '23',],
            ['title' => 'جلگه چاه هاشم', 'province_id' => '23',],
            ['title' => 'جهان‌تیغ زابل', 'province_id' => '23',],
            ['title' => 'جکیگور چابهار', 'province_id' => '23',],
            ['title' => 'چابهار (منطقه آزاد)', 'province_id' => '23',],
            ['title' => 'چاه شور', 'province_id' => '23',],
            ['title' => 'چچاه گیجی', 'province_id' => '23',],
            ['title' => 'حسن خون', 'province_id' => '23',],
            ['title' => 'حمیری', 'province_id' => '23',],
            ['title' => 'حیط', 'province_id' => '23',],
            ['title' => 'خاش زاهدان', 'province_id' => '23',],
            ['title' => 'خمر', 'province_id' => '23',],
            ['title' => 'خمک زابل', 'province_id' => '23',],
            ['title' => 'خوشین', 'province_id' => '23',],
            ['title' => 'دامن زاهدان', 'province_id' => '23',],
            ['title' => 'دلگان ایرانشهر', 'province_id' => '23',],
            ['title' => 'ده پیران', 'province_id' => '23',],
            ['title' => 'دهپابید زاهدان', 'province_id' => '23',],
            ['title' => 'دهک ایرانشهر', 'province_id' => '23',],
            ['title' => 'دوست محمدخان', 'province_id' => '23',],
            ['title' => 'راسک چابهار', 'province_id' => '23',],
            ['title' => 'رمین چابهار', 'province_id' => '23',],
            ['title' => 'ریگ ملک زاهدان', 'province_id' => '23',],
            ['title' => 'زابل', 'province_id' => '23',],
            ['title' => 'مهرستان', 'province_id' => '23',],
            ['title' => 'زهک زابل', 'province_id' => '23',],
            ['title' => 'ژاله‌ای زابل', 'province_id' => '23',],
            ['title' => 'ساربوک چابهار', 'province_id' => '23',],
            ['title' => 'سبزگز پشتکوه', 'province_id' => '23',],
            ['title' => 'سراوان', 'province_id' => '23',],
            ['title' => 'سرباز ایرانشهر', 'province_id' => '23',],
            ['title' => 'سرگه', 'province_id' => '23',],
            ['title' => 'سنگان', 'province_id' => '23',],
            ['title' => 'سوران ایرانشهر', 'province_id' => '23',],
            ['title' => 'سکوهه زابل', 'province_id' => '23',],
            ['title' => 'سیرکان بم پشت', 'province_id' => '23',],
            ['title' => 'سیب سولان', 'province_id' => '23',],
            ['title' => 'سیف‌آباد', 'province_id' => '23',],
            ['title' => 'شاردر', 'province_id' => '23',],
            ['title' => 'شهردراز', 'province_id' => '23',],
            ['title' => 'شهرک (قرقری)', 'province_id' => '23',],
            ['title' => 'صدیق‌زهی چابهار', 'province_id' => '23',],
            ['title' => 'علی‌آباد سرباز', 'province_id' => '23',],
            ['title' => 'عورکی چابهار', 'province_id' => '23',],
            ['title' => 'فنوج ایرانشهر', 'province_id' => '23',],
            ['title' => 'قصرقند چابهار', 'province_id' => '23',],
            ['title' => 'قلعه نو زابل', 'province_id' => '23',],
            ['title' => 'کنارک چابهار', 'province_id' => '23',],
            ['title' => 'کنت ایرانشهر', 'province_id' => '23',],
            ['title' => 'کهک زابل', 'province_id' => '23',],
            ['title' => 'کهیر چابهار', 'province_id' => '23',],
            ['title' => 'کوپچ ایرانشهر', 'province_id' => '23',],
            ['title' => 'کوه میتک', 'province_id' => '23',],
            ['title' => 'گشت ایرانشهر', 'province_id' => '23',],
            ['title' => 'گلخانی', 'province_id' => '23',],
            ['title' => 'گوری زابل', 'province_id' => '23',],
            ['title' => 'گوهرکوه (تمندان)', 'province_id' => '23',],
            ['title' => 'لهاباد', 'province_id' => '23',],
            ['title' => 'لوتک', 'province_id' => '23',],
            ['title' => 'مجتمع (علی اکبر)', 'province_id' => '23',],
            ['title' => 'مجتمع (محمدشاه کرم)', 'province_id' => '23',],
            ['title' => 'محمدآباد', 'province_id' => '23',],
            ['title' => 'محمدآباد زابل', 'province_id' => '23',],
            ['title' => 'مسکوتان', 'province_id' => '23',],
            ['title' => 'ملک حیدری', 'province_id' => '23',],
            ['title' => 'میان‌کنگی', 'province_id' => '23',],
            ['title' => 'میرآباد', 'province_id' => '23',],
            ['title' => 'میرجاوه زاهدان', 'province_id' => '23',],
            ['title' => 'میلک', 'province_id' => '23',],
            ['title' => 'ناصری زاهدان', 'province_id' => '23',],
            ['title' => 'ناهوک کوپک', 'province_id' => '23',],
            ['title' => 'نجف‌آباد زاهدان', 'province_id' => '23',],
            ['title' => 'نصرت‌آباد', 'province_id' => '23',],
            ['title' => 'نصیرآباد', 'province_id' => '23',],
            ['title' => 'نگور چابهار', 'province_id' => '23',],
            ['title' => 'نوبندیان', 'province_id' => '23',],
            ['title' => 'نوک‌آباد زاهدان', 'province_id' => '23',],
            ['title' => 'نوک جوب ایرانشهر', 'province_id' => '23',],
            ['title' => 'نیکشهر چابهار', 'province_id' => '23',],
            ['title' => 'هدار بافتان', 'province_id' => '23',],
            ['title' => 'هیت چابهار', 'province_id' => '23',],
            ['title' => 'هیدوج ایرانشهر', 'province_id' => '23',],
            ['title' => 'کوپچ نیکشهر', 'province_id' => '23',],

            ['title' => 'یزد', 'province_id' => '24',],
            ['title' => 'میبد', 'province_id' => '24',],
            ['title' => 'اردکان', 'province_id' => '24',],
            ['title' => 'حمیدیا', 'province_id' => '24',],
            ['title' => 'بافق', 'province_id' => '24',],
            ['title' => 'مهریز', 'province_id' => '24',],
            ['title' => 'ابرکوه', 'province_id' => '24',],
            ['title' => 'شاهدیه', 'province_id' => '24',],
            ['title' => 'تفت', 'province_id' => '24',],
            ['title' => 'اشکذر', 'province_id' => '24',],
            ['title' => 'هرات', 'province_id' => '24',],
            ['title' => 'زارچ', 'province_id' => '24',],
            ['title' => 'مروست', 'province_id' => '24',],
            ['title' => 'بهاباد', 'province_id' => '24',],
            ['title' => 'مهردشت', 'province_id' => '24',],
            ['title' => 'بفروئیه', 'province_id' => '24',],
            ['title' => 'احمدآباد', 'province_id' => '24',],
            ['title' => 'ندوشن', 'province_id' => '24',],
            ['title' => 'عقدا', 'province_id' => '24',],
            ['title' => 'نیر', 'province_id' => '24',],
            ['title' => 'خضرآباد', 'province_id' => '24',],

            ['title' => 'همدان', 'province_id' => '25',],
            ['title' => 'ملایر', 'province_id' => '25',],
            ['title' => 'نهاوند', 'province_id' => '25',],
            ['title' => 'اسدآباد', 'province_id' => '25',],
            ['title' => 'تویسرکان', 'province_id' => '25',],
            ['title' => 'بهار', 'province_id' => '25',],
            ['title' => 'کبودرآهنگ', 'province_id' => '25',],
            ['title' => 'لالجین', 'province_id' => '25',],
            ['title' => 'فامنین', 'province_id' => '25',],
            ['title' => 'رزن', 'province_id' => '25',],
            ['title' => 'قروه درجزین', 'province_id' => '25',],
            ['title' => 'مریانج', 'province_id' => '25',],
            ['title' => 'ازندریان', 'province_id' => '25',],
            ['title' => 'جورقان', 'province_id' => '25',],
            ['title' => 'گیان', 'province_id' => '25',],
            ['title' => 'صالح‌آباد', 'province_id' => '25',],
            ['title' => 'فیروزان', 'province_id' => '25',],
            ['title' => 'سامن', 'province_id' => '25',],
            ['title' => 'سرکان', 'province_id' => '25',],
            ['title' => 'دمق', 'province_id' => '25',],
            ['title' => 'قهاوند', 'province_id' => '25',],
            ['title' => 'شیرین‌سو', 'province_id' => '25',],
            ['title' => 'برزول', 'province_id' => '25',],
            ['title' => 'گل‌تپه', 'province_id' => '25',],
            ['title' => 'جوکار', 'province_id' => '25',],
            ['title' => 'فرسفج', 'province_id' => '25',],
            ['title' => 'زنگنه', 'province_id' => '25',],

            ['title' => 'ابوموسی', 'province_id' => '26',],
            ['title' => 'بستک', 'province_id' => '26',],
            ['title' => 'بندر چارک', 'province_id' => '26',],
            ['title' => 'بندر خمیر', 'province_id' => '26',],
            ['title' => 'بندر لنگه', 'province_id' => '26',],
            ['title' => 'بندر عباس', 'province_id' => '26',],
            ['title' => 'جاسک', 'province_id' => '26',],
            ['title' => 'جناح', 'province_id' => '26',],
            ['title' => 'حاجی‌آباد', 'province_id' => '26',],
            ['title' => 'دهبارز', 'province_id' => '26',],
            ['title' => 'قشم', 'province_id' => '26',],
            ['title' => 'کیش', 'province_id' => '26',],
            ['title' => 'میناب', 'province_id' => '26',],
            ['title' => 'سوزا', 'province_id' => '26',],
            ['title' => 'سیریک', 'province_id' => '26',],
            ['title' => 'فین', 'province_id' => '26',],
            ['title' => 'کنگ', 'province_id' => '26',],
            ['title' => 'درگهان', 'province_id' => '26',],
            ['title' => 'زیارت‌علی', 'province_id' => '26',],
            ['title' => 'فارغان', 'province_id' => '26',],
            ['title' => 'گاوبندی', 'province_id' => '26',],
            ['title' => 'هرمز', 'province_id' => '26',],
            ['title' => 'رویدر', 'province_id' => '26',],

            ['title' => 'آمل', 'province_id' => '27',],
            ['title' => 'بابل', 'province_id' => '27',],
            ['title' => 'بابلسر', 'province_id' => '27',],
            ['title' => 'بهشهر', 'province_id' => '27',],
            ['title' => 'تنکابن', 'province_id' => '27',],
            ['title' => 'جویبار', 'province_id' => '27',],
            ['title' => 'چالوس', 'province_id' => '27',],
            ['title' => 'رامسر', 'province_id' => '27',],
            ['title' => 'ساری', 'province_id' => '27',],
            ['title' => 'سوادکوه', 'province_id' => '27',],
            ['title' => 'قائمشهر', 'province_id' => '27',],
            ['title' => 'گلوگاه', 'province_id' => '27',],
            ['title' => 'محمودآباد', 'province_id' => '27',],
            ['title' => 'نکا', 'province_id' => '27',],
            ['title' => 'نور', 'province_id' => '27',],
            ['title' => 'نوشهر', 'province_id' => '27',],
            ['title' => 'فریدونکنار', 'province_id' => '27',],
            ['title' => 'عباس‌آباد', 'province_id' => '27',],
            ['title' => 'میاندورود', 'province_id' => '27',],

            ['title' => 'گرگان', 'province_id' => '28',],
            ['title' => 'بندرترکمن', 'province_id' => '28',],
            ['title' => 'بندرگز', 'province_id' => '28',],
            ['title' => 'مینودشت', 'province_id' => '28',],
            ['title' => 'علی آباد', 'province_id' => '28',],
            ['title' => 'گنبدکاووس', 'province_id' => '28',],
            ['title' => 'کردکوی', 'province_id' => '28',],
            ['title' => 'آزادشهر', 'province_id' => '28',],
            ['title' => 'القجر', 'province_id' => '28',],
            ['title' => 'بالاجاده', 'province_id' => '28',],
            ['title' => 'تقی آباد', 'province_id' => '28',],
            ['title' => 'چین سوبلی', 'province_id' => '28',],
            ['title' => 'خواجه نفس', 'province_id' => '28',],
            ['title' => 'دوزالوم', 'province_id' => '28',],
            ['title' => 'سارجه گر', 'province_id' => '28',],
            ['title' => 'سلاق غایب', 'province_id' => '28',],
            ['title' => 'فاضل آباد', 'province_id' => '28',],
            ['title' => 'قره بلاغ', 'province_id' => '28',],
            ['title' => 'کوچک خرطوم', 'province_id' => '28',],
            ['title' => 'مراوه تپه', 'province_id' => '28',],
            ['title' => 'نودیجه', 'province_id' => '28',],
            ['title' => 'آق آباد', 'province_id' => '28',],
            ['title' => 'امیرآباد', 'province_id' => '28',],
            ['title' => 'بی بی شیروان', 'province_id' => '28',],
            ['title' => 'تمر قره قوزی', 'province_id' => '28',],
            ['title' => 'حاجی قوشان', 'province_id' => '28',],
            ['title' => 'دارکلاته', 'province_id' => '28',],
            ['title' => 'دوزین', 'province_id' => '28',],
            ['title' => 'سارلی سفلی', 'province_id' => '28',],
            ['title' => 'سلطانعلی', 'province_id' => '28',],
            ['title' => 'فجر', 'province_id' => '28',],
            ['title' => 'کاکا', 'province_id' => '28',],
            ['title' => 'گالیکش', 'province_id' => '28',],
            ['title' => 'مزرعه کتول', 'province_id' => '28',],
            ['title' => 'نوکنده', 'province_id' => '28',],
            ['title' => 'آق قلا', 'province_id' => '28',],
            ['title' => 'انبار آلوم', 'province_id' => '28',],
            ['title' => 'پیراوش سفلی', 'province_id' => '28',],
            ['title' => 'تنگراه و ترجنلی', 'province_id' => '28',],
            ['title' => 'حاجی کلاته', 'province_id' => '28',],
            ['title' => 'دلند', 'province_id' => '28',],
            ['title' => 'رامیان', 'province_id' => '28',],
            ['title' => 'سرخن کلاته', 'province_id' => '28',],
            ['title' => 'شاهکوه سفلی', 'province_id' => '28',],
            ['title' => 'قارتی و بناور', 'province_id' => '28',],
            ['title' => 'کرم آباد', 'province_id' => '28',],
            ['title' => 'لیوان', 'province_id' => '28',],
            ['title' => 'نظام آباد', 'province_id' => '28',],
            ['title' => 'یلمه سالیان', 'province_id' => '28',],
            ['title' => 'ارازگل و لاله باغ', 'province_id' => '28',],
            ['title' => 'اینچه برون', 'province_id' => '28',],
            ['title' => 'تاتارعلیا', 'province_id' => '28',],
            ['title' => 'جلین علیا', 'province_id' => '28',],
            ['title' => 'خان ببین', 'province_id' => '28',],
            ['title' => 'دنگلان', 'province_id' => '28',],
            ['title' => 'رضاآباد', 'province_id' => '28',],
            ['title' => 'سرکلاته خرابه شهر', 'province_id' => '28',],
            ['title' => 'عطاآباد', 'province_id' => '28',],
            ['title' => 'قرق', 'province_id' => '28',],
            ['title' => 'کلاله', 'province_id' => '28',],
            ['title' => 'محمدآباد', 'province_id' => '28',],
            ['title' => 'نوده خاندوز', 'province_id' => '28',],
            ['title' => 'ینقاق و کامران آباد', 'province_id' => '28',],

            ['title' => 'رشت', 'province_id' => '29',],
            ['title' => 'آستارا', 'province_id' => '29',],
            ['title' => 'رودبار', 'province_id' => '29',],
            ['title' => 'فومن', 'province_id' => '29',],
            ['title' => 'آستانه اشرفیه', 'province_id' => '29',],
            ['title' => 'رودسر', 'province_id' => '29',],
            ['title' => 'لاهیجان', 'province_id' => '29',],
            ['title' => 'بندرانزلی', 'province_id' => '29',],
            ['title' => 'شفت', 'province_id' => '29',],
            ['title' => 'لنگرود', 'province_id' => '29',],
            ['title' => 'صومعه سرا', 'province_id' => '29',],
            ['title' => 'هشتپر', 'province_id' => '29',],

            ['title' => 'خرم‌آباد', 'province_id' => '30',],
            ['title' => 'بروجرد', 'province_id' => '30',],
            ['title' => 'درود', 'province_id' => '30',],
            ['title' => 'کوهدشت', 'province_id' => '30',],
            ['title' => 'الیگودرز', 'province_id' => '30',],
            ['title' => 'نورآباد', 'province_id' => '30',],
            ['title' => 'ازنا', 'province_id' => '30',],
            ['title' => 'الشتر', 'province_id' => '30',],
            ['title' => 'پل‌دختر', 'province_id' => '30',],
            ['title' => 'کونانی', 'province_id' => '30',],
            ['title' => 'معمولان', 'province_id' => '30',],
            ['title' => 'چقابل', 'province_id' => '30',],
            ['title' => 'اشترینان', 'province_id' => '30',],
            ['title' => 'گراب', 'province_id' => '30',],
            ['title' => 'فیروزآباد', 'province_id' => '30',],
            ['title' => 'زاغه', 'province_id' => '30',],
            ['title' => 'سپیددشت', 'province_id' => '30',],
            ['title' => 'درب گنبد', 'province_id' => '30',],
            ['title' => 'ویسیان', 'province_id' => '30',],
            ['title' => 'مؤمن‌آباد', 'province_id' => '30',],
            ['title' => 'شول آباد', 'province_id' => '30',],
            ['title' => 'سراب‌دوره', 'province_id' => '30',],
            ['title' => 'چالانچولان', 'province_id' => '30',],
            ['title' => 'چغلوندی', 'province_id' => '30',],
            ['title' => 'هفت چشمه', 'province_id' => '30',],

            ['title' => 'اراک', 'province_id' => '31',],
            ['title' => 'ساوه', 'province_id' => '31',],
            ['title' => 'خمین', 'province_id' => '31',],
            ['title' => 'محلات', 'province_id' => '31',],
            ['title' => 'دلیجان', 'province_id' => '31',],
            ['title' => 'کرهرود', 'province_id' => '31',],
            ['title' => 'شازند', 'province_id' => '31',],
            ['title' => 'مأمونیه', 'province_id' => '31',],
            ['title' => 'تفرش', 'province_id' => '31',],
            ['title' => 'مهاجران', 'province_id' => '31',],
            ['title' => 'سنجان', 'province_id' => '31',],
            ['title' => 'میلاجرد', 'province_id' => '31',],
            ['title' => 'کمیجان', 'province_id' => '31',],
            ['title' => 'آشتیان', 'province_id' => '31',],
            ['title' => 'خنداب', 'province_id' => '31',],
            ['title' => 'آستانه', 'province_id' => '31',],
            ['title' => 'پرندک', 'province_id' => '31',],
            ['title' => 'زاویه', 'province_id' => '31',],
            ['title' => 'نیم ور', 'province_id' => '31',],
            ['title' => 'داودآباد', 'province_id' => '31',],
            ['title' => 'خشکرود', 'province_id' => '31',],
            ['title' => 'غرق آباد', 'province_id' => '31',],
            ['title' => 'جاورسیان', 'province_id' => '31',],
            ['title' => 'فرمهین', 'province_id' => '31',],
            ['title' => 'خنجین', 'province_id' => '31',],
            ['title' => 'کارچان', 'province_id' => '31',],
            ['title' => 'نراق', 'province_id' => '31',],
            ['title' => 'توره', 'province_id' => '31',],
            ['title' => 'نوبران', 'province_id' => '31',],
            ['title' => 'هندودر', 'province_id' => '31',],
            ['title' => 'قورچی باشی', 'province_id' => '31',],
            ['title' => 'ساروق', 'province_id' => '31',],
            ['title' => 'رازقان', 'province_id' => '31',],
            ['title' => 'شهباز', 'province_id' => '31',],
        ];

        foreach ($cities as $key => $value) {
            $obj = new City();
        }
    }
}
